name: Build and Release

on:
  push:
    branches: [main, dev] # Added 'dev' branch to triggers

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore dependencies
        run: msbuild SharpEDRChecker/SharpEDRChecker.sln /t:restore

      - name: Build for AnyCPU
        run: msbuild SharpEDRChecker/SharpEDRChecker.sln /p:Configuration=Release /p:Platform="AnyCPU"

      - name: Build for x64
        run: msbuild SharpEDRChecker/SharpEDRChecker.sln /p:Configuration=Release /p:Platform=x64

      - name: Build for x86
        run: msbuild SharpEDRChecker/SharpEDRChecker.sln /p:Configuration=Release /p:Platform=x86

      - name: Rename artifacts for clarity
        run: |
          $branchName = "${{ github.ref_name }}"
          $outputDir = "SharpEDRChecker/bin"
          $releaseDir = "$outputDir/Release"
          $x64Dir = "$outputDir/x64/Release"
          $x86Dir = "$outputDir/x86/Release"

          if ($branchName -eq "main") {
            Rename-Item -Path "$releaseDir/SharpEDRChecker.exe" -NewName "SharpEDRChecker-AnyCPU.exe"
            Rename-Item -Path "$x64Dir/SharpEDRChecker.exe" -NewName "SharpEDRChecker-x64.exe"
            Rename-Item -Path "$x86Dir/SharpEDRChecker.exe" -NewName "SharpEDRChecker-x86.exe"
          } else {
            Rename-Item -Path "$releaseDir/SharpEDRChecker.exe" -NewName "SharpEDRChecker-AnyCPU-${branchName}.exe"
            Rename-Item -Path "$x64Dir/SharpEDRChecker.exe" -NewName "SharpEDRChecker-x64-${branchName}.exe"
            Rename-Item -Path "$x86Dir/SharpEDRChecker.exe" -NewName "SharpEDRChecker-x86-${branchName}.exe"
          }
        shell: pwsh # Using PowerShell for conditional renaming

      - name: Create Release and Upload Assets (Main Branch)
        if: github.ref == 'refs/heads/main' # Only create release for main branch
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files: |
            SharpEDRChecker/bin/Release/SharpEDRChecker-AnyCPU.exe
            SharpEDRChecker/bin/x64/Release/SharpEDRChecker-x64.exe
            SharpEDRChecker/bin/x86/Release/SharpEDRChecker-x86.exe

      - name: Upload Dev Branch Artifacts
        if: github.ref == 'refs/heads/dev' # Only upload artifacts for dev branch
        uses: actions/upload-artifact@v4
        with:
          name: SharpEDRChecker-dev-build-${{ github.run_number }}
          path: |
            SharpEDRChecker/bin/Release/SharpEDRChecker-AnyCPU-dev.exe
            SharpEDRChecker/bin/x64/Release/SharpEDRChecker-x64-dev.exe
            SharpEDRChecker/bin/x86/Release/SharpEDRChecker-x86-dev.exe
